const VIBRATION_DURATION_ON_COUNTER_CLICK = 15;
const COUNTER_SQL_TABLE_NAME = 'counters';
const COUNTER_ASYNC_STORE_NAME = 'counter-store';

export {
	VIBRATION_DURATION_ON_COUNTER_CLICK,
	COUNTER_SQL_TABLE_NAME,
	COUNTER_ASYNC_STORE_NAME
};
